export const sectorNameMapping: Record<string, string> = {
  'HEBERGEMENT ET SERVICES DE RESTAURATION': 'HEBERGEMENT ET RESTAURATION',
  'FORESTERIE, EXPLOITATION FORESTIERE ET ACTIVITES DE SOUTIEN A LA FORESTERIE':
    'FORESTERIE ET EXPLOITATION FORESTIERE',
  'SERVICES IMMOBILIERS ET SERVICES DE LOCATION ET DE LOCATION A BAIL':
    'SERVICES IMMOBILIERS ET SERVICES DE LOCATION',
  'EXTRACTION MINIERE, EXPLOITATION EN CARRIERE ET EXTRACTION DE PETROLE ET DE GAZ':
    'EXTRACTION MINIERE, DE PETROLE ET DE GAZ',
  'SERVICES AUX ENTREPRISES, SERVICES RELATIFS AUX BATIMENTS ET AUTRES SERVICES DE SOUTIEN':
    'SERVICES AUX ENTREPRISES ET AUX BATIMENTS',
};
